---
- name: Learn AWX privilege escalation
  hosts: web
  gather_facts: false

  tasks:
    - name: Show normal SSH user
      ansible.builtin.command:
        cmd: whoami
      register: normal_user
      changed_when: false

    - name: Display normal user
      ansible.builtin.debug:
        msg: "Normal user = {{ normal_user.stdout }}"

    - name: Show privileged user
      become: true
      ansible.builtin.command:
        cmd: whoami
      register: privileged_user
      changed_when: false

    - name: Display privileged user
      ansible.builtin.debug:
        msg: "Privileged user = {{ privileged_user.stdout }}"

    - name: Create protected file
      become: true
      ansible.builtin.copy:
        content: "Created by AWX using Ansible become\n"
        dest: /etc/awx-lab-test
        owner: root
        group: root
        mode: "0644"