---
- name: Learn AWX credentials
  hosts: web
  gather_facts: false

  tasks:
    - name: Show SSH login user
      ansible.builtin.command:
        cmd: whoami
      register: login_user
      changed_when: false

    - name: Display SSH login user
      ansible.builtin.debug:
        msg: "SSH execution user = {{ login_user.stdout }}"

    - name: Show current user ID
      ansible.builtin.command:
        cmd: id
      register: user_id
      changed_when: false

    - name: Display user ID
      ansible.builtin.debug:
        var: user_id.stdout