---
- name: Inspect AWX inventory
  hosts: web
  gather_facts: false

  tasks:
    - name: Show host
      ansible.builtin.debug:
        msg: "inventory_hostname = {{ inventory_hostname }}"

    - name: Show groups
      ansible.builtin.debug:
        var: group_names

    - name: Show environment
      ansible.builtin.debug:
        var: environment

    - name: Show server role
      ansible.builtin.debug:
        var: server_role

    - name: Show app port
      ansible.builtin.debug:
        var: app_port