---
- name: Cisco NX-OS first AWX test
  hosts: cisco_nxos
  gather_facts: false

  tasks:
    - name: Gather NX-OS facts
      cisco.nxos.nxos_facts:
        gather_subset:
          - min

    - name: Display Nexus information
      ansible.builtin.debug:
        msg:
          - "Inventory host = {{ inventory_hostname }}"
          - "Hostname = {{ ansible_net_hostname | default('unknown') }}"
          - "Model = {{ ansible_net_model | default('unknown') }}"
          - "Serial = {{ ansible_net_serialnum | default('unknown') }}"
          - "NX-OS Version = {{ ansible_net_version | default('unknown') }}"

    - name: Run show version
      cisco.nxos.nxos_command:
        commands:
          - show version
      register: nxos_show_version_result

    - name: Display show version
      ansible.builtin.debug:
        var: nxos_show_version_result.stdout_lines
